[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pythonnn"
version = "0.1.12"
authors = [
  { name="bestcode123", email="" },
]
description = "A bare neural network package made for optimization"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/bestcode123/pythonnn"
"Bug Tracker" = "https://github.com/bestcode123/pythonnn"